# -*- coding: utf-8 -*-
# Generated by pyrcc5 from resources.qrc

from PyQt5.QtCore import QResource, QIODevice, QFile, QDataStream

class Resources:
    @staticmethod
    def initialize():
        resource_file = QFile(":/plugins/resources.qrc")
        resource_file.open(QIODevice.ReadOnly)
        QResource.registerResource(resource_file)
